baseurl = "https://sebastienflochlay.github.io/AutoEcoleBlagnac/"
#baseURL = "http://example.org/"
title = "Universal"
theme = "hugo-universal-theme"
publishDir = "docs"
languageCode = "fr"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Auto"
    url  = "/auto/"
    weight = 2

[[menu.main]]
    name = "Moto"
    url  = "/moto/"
    weight = 3

[[menu.main]]
    name = "Stage"
    url  = "#"
    weight = 4

[[menu.main]]
    name = "Fiches"
    url  = "/blog/"
    weight = 5

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 6

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 7

# Copyright bar social links menu

[[menu.copyrightbar]]
    weight = 1
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.copyrightbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.copyrightbar]]
    weight = 3
    name = "Email"
    url = "mailto:info@automotoblagnac.com "
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Sebastien"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
    googleMapsApiKey = "AIzaSyCehnEsuyKgFAjZscs_5bhBdiEh5XYsGw4"
#    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@automotoblagnac.com"

    about_us = """<p>Une école pas comme les autres pour passer votre permis.</p>
                <p>Ici à l'auto-moto école du plateau toulouse blagnac, nous sommes specialisés en formation permis auto moto et stage de perfectionnement moto."""
    copyright = "Copyright (c) 2015-2017 -- Auto Moto ecole du plateau Blagnac -- All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"

    timeslot = """<p><strong>Lundi-Vendredi</strong> : 14h00 – 19h30
        <br><strong>Samedi</strong> : 10h30 – 13h00
      </p>
      """
    contact = """<p><strong><a href="mailto:">info@automotoblagnac.com</a></strong>
            <br><strong><a href="#">Accueil</a></strong> : 05-61-71-40-56
            <br><strong><a href="#">Stage</a></strong> : 06-03-92-06-11</p>
      """
    address = """<p><strong>Auto / Moto Ecole du Plateau</strong>
        <br>10 Route de Grenade
        <br>31700 Blagnac
      </p>
      """
    latitude = "43.624108"
    longitude = "1.394548"
    direction = "Auto Ecole du Plateau, 10 Route de Grenade, 31700 Blagnac"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.teammembers]
    enable = true
    title = "Venez rencontrer notre équipe"
    subtitle = "Notre équipe, toujours souriante et attentionnée, sera véritablement heureuse de vous rencontrer et de vous accompagner dans cette étape si importante qu'est l'obtention d'un permis. Voici les personnes qui seront là pour vous :"

[params.footer]
    title = "Intéressé, vous désirez en savoir plus ?"
    subtitle = "Contactez-nous"

[params.counters]
    enable = true

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    # title = "Testimonials"
    title = "Témoignages"
    subtitle = "Nous avons formé et accompagné de nombreuses personnes depuis notre création, et nous sommes toujours heureux de voir que l'obtention du permis est toujours un instant important. Prenez un instant pour regarder ce qu'ils pensent de nous."

[params.see_more_permisauto]
    enable = true
    enablefixe = true
    icon = "fa fa-car"
    title = "Intéressé par le permis voiture ?"
    subtitle = "Fort de leurs 26 ans d’expérience les formateurs de l’auto moto école du plateau Toulouse Blagnac sauront trouver les mots afin de vous faire progresser.ils vous accompagneront au mieux au cours de votre formation pour évoluer rapidement."
    link_url = "/permisauto"
    link_text = "Venez voir nos offres"

[params.see_more_permismoto]
    enable = true
    enablefixe = true
    icon = "fa fa-motorcycle"
    title = "Vous êtes plutôt permis moto ?"
    subtitle = "Jean-Marc, le formateur de l’Auto Moto Ecole du Plateau Toulouse Blagnac, vous guidera sur la route de votre réussite."
    link_url = "/permismoto"
    link_text = "Venez voir notre offre"

[params.see_more_perfectionnement]
    enable = true
    enablefixe = true
    icon = "fa fa-motorcycle"
    title = "Vous désirez effectuer un stage de perfectionnement ?"
    subtitle = "Si comme beaucoup, votre sécurité à moto vous préoccupe, ce stage de perfectionnement vous rassurera !"
    link_url = "/perfectionnement"
    link_text = "Venez voir notre offre"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Nos partenaires"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Découvrez nos fiches explicatives"
    subtitle = "Nos formateurs vous ont préparer quelques fiches explicatives qui j'en suis sûr, vous seront très utiles. Retrouvez ici des aides, explications et trucs-et-astuces qui vous permettront d'intégrer plus vite ce que vous aurez vu en cours..."
